### ISSUE TITLE
existence check:  moab to catalog

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/preservation_core_catalog#107]
code to, given info from online Moab, confirm existence of PCC 

(basically, use preserved_object.update  (or, rest call)

**Comment by SaravShah** [comment]
Moab to Inventory validation
The Moab objects stores can be considered “truth” for Preservation Core, since no metadata claims to the contrary will make the object any different. We start with this audit to assure the Preservation Core Catalog is aligned with this base information.

Business Value
An ongoing inventory check will help assure the completeness and accuracy of the PC metadata that other systems like Argo will rely on to determine the state of objects in Preservation Core. It will also alert us to any cases where this information manages to get out of sync.
MVP
Verifies 1-to-1 druid and version match of Moab object store with PCC entries
Run continuously, with a cycle time of under a week 
this is a hypothetical minimum that would allow us to finish this work effort, with performance work needed in the future
our target is to be able to check all storage roots in 24 hour
Any inconsistencies in the Inventory should be updated to match what is actually in Moab storage, and the discrepancy logged/reported (but not included in Provenance)

**Comment by SaravShah** [comment]
https://docs.google.com/document/d/1jmmTQnHaaKnC1dubXrnvdSPpuFQs1KHGnWe9DSv_u_U/edit?ts=59a5c7c8#

Moab to Inventory Validation Header

**Comment by ndushay** [comment]
really, #131 should get done first but can start on this.

Also note that I just heard from VW that everything should be via ReST calls so we can replicate and separate to scale better (!).  So it may also depend on #72
