### ISSUE TITLE
PCC: Reconcile schema with new info

### ISSUE THREAD

**Issue by julianmorley** [sul-dlss/preservation_core_catalog#46]
See:
![sdr-pc ois v3](https://user-images.githubusercontent.com/8161286/29797985-0ab543f0-8c0f-11e7-836f-487c3d347a40.png)
@jmartin-sul, @SaravShah and I hashed this out.

**Comment by ndushay** [comment]
How does this related to #38?

**Comment by jmartin-sul** [comment]
@julianmorley would like the following schema changes, compared to the schema defined by #43:
* julian would like to get rid of the CREATED_AT column on our tables.  he doesn't expect us to use that information, and he'd like us to not waste space on it.
* ENDPOINT_TYPE and PRESERVATION_POLICY should be separate tables, not string cols in their current respective tables.  the reasons are:
  ** endpoint type info will require multiple columns (as per the above diagram), and so should not live as a single string column on the ENDPOINTS table.
  ** PRESERVATION_POLICY is a separate table because we want to be able to define the preservation policy to be used for a specific object (PRESERVED_OBJECT.PPID), as well as being able to define the preservation policy implemented by a given endpoint (via the PRES_POLICY_ENDPOINTS intermediary table).
* STATUS is a separate table because we want to be able to index the status column efficiently, which will be better accomplished using ints than strings, but we still want a list of status code to status text translations.  and besides the indexing efficiency, this will also keep down the space usage of the table we expect to have the largest number of rows (PRESERVATION_COPIES).  this also allows us to easily constrain status values via a foreign key constraint, though we could also constrain the allowed values in the code, if that were the sole motivation for the STATUS table.
* recovery cost is on the ENDPOINTS table (instead of the ENDPOINT_TYPE table) because the same endpoint type in multiple locations could have differing costs.
