### ISSUE TITLE
existence check (PreservedObject.update) - version diffs -  handle all cases

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/preservation_core_catalog#90]
The below is vetted as the desired spec

- when incoming version and db version are the same
  - update timestamp to show it's been checked

- when incoming version is newer than db version:
   - log WARNING 
   - update db version and timestamp

- when incoming version is OLDER than db version
  - log ERROR
       - in new logging approach and/or  
       - in honeybadger and/or 
       - sending email and/or 
       - workflow status update
  - this is a serious problem;  manual intervention

**Comment by ndushay** [comment]
Our *inner method*  (not API) has tests showing our current implementation decisions:

```
PreservedObject
  should belong to preservation_policy
  should have many preservation_copies
  should have an index on columns druid
  should have an index on columns preservation_policy_id
  validation
    is valid with required attributes
    is valid with required and optional attributes
    is not valid without attributes
    is not valid without a druid
    is not valid without a current_version
    enforces unique constraint on druid
  .update
    entry already exists
      incoming and db versions match
        entry version stays the same
        logs at info level
        behaves like entry exists
          updates entry with timestamp
          logs at debug level
          returns true
      incoming version is greater than db version
        updates entry with incoming version
        logs at info level
        behaves like entry exists
          updates entry with timestamp
          logs at debug level
          returns true
      incoming version is smaller than db version
        entry version stays the same
        logs at warn level
        behaves like entry exists
          updates entry with timestamp
          logs at debug level
          returns true
    entry does not exist (yet)
      creates entry
      logs at warn level
      returns false

```

**Comment by julianmorley** [comment]
This problem needs to be considered with an eye towards how this info is stored in the database; but generally - if this is an Online Moab - we'll have a record in the database that says, "This online Moab, on storage root 1, of druid aa123bb1234, is at version 7". If the Inventory process/function discovers, "This online Moab, on storage root 1, of druid aa123bb1234, is at version 5", then it implies that that particular Moab has changed between runs of the inventory process - it's somehow lost two versions. In this case, this should prompt two things: 
* Alert like crazy, because we've just found evidence of data loss
* Attempt to recover that druid to version 7, using either another Online copy in a different storage root, or by restoring it from an archived copy of version 7.
