### ISSUE TITLE
Get performance goals into MVP

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/preservation_core_catalog#95]
@LynnMcRae @julianmorley

We would like clearly stated performance targets for various functionality, e.g.:

- inventory:  seed the prod db from current production drives
- inventory:  run a check against all online moabs

- audit:  seed the checksums from current production drives
- audit: run a complete check against all online moabs

etc.

**Comment by julianmorley** [comment]
Generally, initial ingest doesn't have any performance requirements given that it's not going to be a common event. 
How about:
* Any one storage_root should be capable of being inventoried in less than 2 hours. (we currently have 11 storage roots, so that means if run in serial, we should be capable of inventorying all our disks within 22 hours).
* Audit should be capable of fixity checking every online Moab at least once every 10 days.
* No explicit performance requirements around initial checksum creation

**Comment by ndushay** [comment]
@LynnMcRae   I have altered this ticket title -- I would like the MVP to reflect performance expectations something akin to the info in his comment.   (We agreed on time to check existence for storage_roots today ... would also like "audit" expressed)

**Comment by ndushay** [comment]
I am closing this dev ticket as I think the new MVP and supporting docs reflect this information (yay!)
