### ISSUE TITLE
benchmark checksum calculations

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/preservation_core_catalog#96]
Very large object checksum calculations can be resource hungry.

We should get some benchmark data for files of various sizes, including the largest objects we would have.

Notes:
- Thib gave some excellent advice for java checksum calculations for wasapi-downloader
- Ben's objects in dropbox are media objects

**Comment by jmartin-sul** [comment]
see https://github.com/sul-dlss/wasapi-downloader/pull/122

**Comment by julianmorley** [comment]
Huh, the wasapi code also went with an 8K buffer - essentially forcing lots of small block reads. That's bad. There's a huge difference in throughput between reading a large file in 8K chunks, and reading it in 256K chunks - 32x I/O waits!

Remember that to properly benchmark this you need to purge the page cache on the test box between tests, otherwise the test file just lives in RAM and I/O waits are no longer a problem. I would recommend a test file of at least 10MB in size, preferably 1GB.

**Comment by tingulfsen** [comment]
See https://github.com/sul-dlss/moab-versioning/blob/2beb8ed8448c5a3952e75bd80a59ecf897ab154f/lib/moab/file_signature.rb#L144-L163

and

https://github.com/sul-dlss/wasapi-downloader/blob/master/src/edu/stanford/dlss/was/WasapiValidator.java#L72-L91
